// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsO3h-KzUE7qIWJIHfwDvtDC4Q649n2R8',
    appId: '1:199434318932:web:6d143b550297d83dada9c1',
    messagingSenderId: '199434318932',
    projectId: 'pizza-delivery-app-94b4f',
    authDomain: 'pizza-delivery-app-94b4f.firebaseapp.com',
    storageBucket: 'pizza-delivery-app-94b4f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_yCMRlTTD1tvMjcAN04RA8eIaUNgxpkY',
    appId: '1:199434318932:android:7382a02a8c171d7dada9c1',
    messagingSenderId: '199434318932',
    projectId: 'pizza-delivery-app-94b4f',
    storageBucket: 'pizza-delivery-app-94b4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90Mo10NGkUibv0nxIiJjiwHqTCS0dJlA',
    appId: '1:199434318932:ios:7ab833ae89d6a9f8ada9c1',
    messagingSenderId: '199434318932',
    projectId: 'pizza-delivery-app-94b4f',
    storageBucket: 'pizza-delivery-app-94b4f.firebasestorage.app',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );
}
